
# placeholder
name: PR Decoration, Dockerize Java App and Deploy on EC2 with ASG

# events on which pipeline will run
on: 
  #push:
    #branches: [ master ]
  #pull_request:
    #branches: [ master ]
  workflow_dispatch:
    inputs:
      parameter_name:
        description: 'manually running jobs'
        required: true
jobs:
  build-java:
    runs-on: 'self-hosted'

    steps:
    - name: repository checkout
      uses: actions/checkout@v3

    - name: java setup
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '8'

    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: '3.8.2'

    - name: build with maven
      run: cd ./springboot-backend ; mvn clean install -DskipTests=true
  
  build-angular:
    runs-on: 'self-hosted'
    steps:
      - name: set up Node.js
        uses: actions/setup-node@v3
        with:
            node-version: 16 #you can adjust node version 14,16,18
        
      - name: Install Angular CLI
        run: npm install -g @angular/cli 

      - name: Build Angular app
        run: |
          cd ./"angular app"/app 
          npm install 
          ng build --prod
    
  SonarQube-analysis:
      runs-on: 'self-hosted'
      needs: 'build-java'
      steps:
        - name: SonarQube Scan
          uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
       
  Slack-notification:
       #runs-on: 'self-hosted'
      - name: Send custom JSON data to Slack workflow
        needs: ['build-java','build-angular','SonarQube-analysis']
        steps:
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
        # For posting a rich message using Block Kit
        payload: |
         {
        "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
        "blocks": [
          {
            "type": "section",
            "text": {
              "type": "mrkdwn",
              "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
            }
          }
         ]
        }
       env:
       SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
       SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
